; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = release

[env:release]
platform = espressif32 @ 6.5.0
board = m5stick-c
lib_ldf_mode = deep
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = min_spiffs.csv

build_type = debug

lib_deps =
      https://github.com/scuba-hacker/M5StickC-Plus#UseExternalTFT_eSPI
      https://github.com/scuba-hacker/TFT_eSPI#PushImageScaled
  	  olikraus/U8g2 @ 2.36.12

build_unflags = -std=gnu++11

; -D build options are for TFT_eSPI so that UserSetup.h does not need to be read

build_flags = 
  -std=gnu++17
  -D TARGET_M5STICKC_PLUS=1

  -D USER_SETUP_LOADED=1
  -D DISABLE_ALL_LIBRARY_WARNINGS=1
  
  ; Define the TFT driver, pins etc here:
  -D ST7789_2_DRIVER=1
  -D TFT_SDA_READ=1
  -D TFT_RGB_ORDER=TFT_RGB
  -D TFT_WIDTH=135
  -D TFT_HEIGHT=240
; -D TFT_MISO=
  -D TFT_MOSI=15
  -D TFT_SCLK=13
  -D TFT_CS=5
  -D TFT_DC=23
  -D TFT_RST=18
  -D TFT_BL=PIN_D1

  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D LOAD_FONT6=1
  -D LOAD_FONT7=1
  -D LOAD_FONT8=1
  -D LOAD_GFXFF=1
  -D SMOOTH_FONT=1
  -D SPI_FREQUENCY=27000000
  -D SPI_READ_FREQUENCY=20000000

[env:esp32c3]
platform = espressif32 @ 6.5.0
board = dfrobot_beetle_esp32c3
lib_ldf_mode = deep
framework = arduino
upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = min_spiffs.csv

build_type = debug

lib_deps =
      olikraus/U8g2 @ 2.36.12

build_unflags = -std=gnu++11

; Change OLED_SDA/OLED_SCK here if your ESP32-C3 board uses different I2C pins.
build_flags =
  -std=gnu++17
  -D TARGET_M5STICKC_PLUS=0
  -D OLED_SDA=8
  -D OLED_SCK=9

[env:esp32c3_slow]
platform = espressif32 @ 6.5.0
board = dfrobot_beetle_esp32c3
lib_ldf_mode = deep
framework = arduino
upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = min_spiffs.csv
; Valid clock speeds: 10 MHz, 20 MhZ, 40 MHz, 80 MHz, 160 MHz (default)
board_build.f_cpu = 10000000L

build_type = debug

lib_deps =
      olikraus/U8g2 @ 2.36.12

build_unflags = -std=gnu++11

; Change OLED_SDA/OLED_SCK here if your ESP32-C3 board uses different I2C pins.
build_flags =
  -std=gnu++17
  -D TARGET_M5STICKC_PLUS=0
  -D OLED_SDA=8
  -D OLED_SCK=9

